### ISSUE TITLE
Modder please refer to net.minecraftforge.oredict.RecipeSorter

### ISSUE THREAD

**Issue by bochen415** [Outurnate/WarpBook#10]
http://paste.ubuntu.com/9903275/

line 16261+

Unknown recipe class! com.panicnot42.warpbook.crafting.WarpPageShapeless Modder please refer to net.minecraftforge.oredict.RecipeSorter

**Comment by Outurnate** [comment]
Will take a look.  Minor issue

**Comment by Outurnate** [comment]
Fixed in latest commit
