### ISSUE TITLE
Allow blank pages to be placed in the warp book.

### ISSUE THREAD

**Issue by TimB1087** [Outurnate/WarpBook#12]
Enchancement.

Allow blank, unbound warp pages to be stores inside the warp book. I often find myself running back to my home to make/grab more warp pages, just so I can use a /back command to save the warp location of an interesting or useful place.

Sometimes players don't go somewhere in the world with the intention of finding places to save, but might instead stumble upon something useful to them, and want to save that location. Warping home to get more pages would cause them to lose that location, unless of course they have a command to get them back, which we can not expect to always be the case.

Players also tend to like to keep their inventory as empty as possible, especially when collecting resources. Having the ability to store extra pages inside the warp book could be very beneficial, and in my opinion, a great feature for this mod.

**Comment by Outurnate** [comment]
Will include
Which version - TBA

**Comment by Outurnate** [comment]
In the current master build.  Not prod ready yet, but on the way

**Comment by Outurnate** [comment]
Closing - will be in next release
