### ISSUE TITLE
To close warpbook with Inventory Key

### ISSUE THREAD

**Issue by Zaflis** [Outurnate/WarpBook#14]
This should be easy to implement. Currently when i open Warpbook it can only be cancelled with ESC key. I have bound my inventory to E key, now unsure if it's default for it in Minecraft or not. Either way you should be able to use inventory key for closing the screen. Many other mods, such as different machine UI's already support it.

(Using Minecraft 1.7.10)

**Comment by Outurnate** [comment]
Can do.  It's a quick fix

Look for an update this weekend

**Comment by Outurnate** [comment]
Fixed in the current commit.  Will push a new jar in an hour
