### ISSUE TITLE
CompareTo shall be implemented in command classes

### ISSUE THREAD

**Issue by LemADEC** [Outurnate/WarpBook#15]
CompareTo override is invalid in your command classes, this prevent the use /help command in-game, please fix it.
Here's one of the instance of this issue: https://github.com/Outurnate/WarpBook/blob/1.7.10/src/main/java/com/panicnot42/warpbook/commands/GiveWarpCommand.java#L78

**Comment by Outurnate** [comment]
42 is invalid? :)

Haven't touched this codebase in a while.  Let me tackle that one now

**Comment by Outurnate** [comment]
Fixed in latest commit
