### ISSUE TITLE
Dimensional White/Black lists

### ISSUE THREAD

**Issue by IMarvinTPA** [Outurnate/WarpBook#17]
I would like a couple white lists and blacklists.
One set of lists for dimensions that may have pages made for them.
Another set of lists that allow you to teleport away from.
Compact machines behaves badly if you just appear in them (wither and other nasty effects.)  So I would like to put its dimension on a blacklist for the pages.  I would also put the Random Thing's spectral key dimension on the pages blacklist.
I don't know how I would use the other lists currently, but they would probably be helpful to somebody.

Thanks,
IMarv

**Comment by Outurnate** [comment]
I toyed with this a while ago.  I will add it

**Comment by Outurnate** [comment]
Implemented in current version
