### ISSUE TITLE
1.8.9 Crash on warp attempt on server

### ISSUE THREAD

**Issue by ZornTaov** [Outurnate/WarpBook#18]
http://pastebin.com/4eGBTLR9

There's the error log on server and client, using 2.0.43, client gets kicked the moment a player uses a warp book page, for both book and a single page.

It looks like com.panicnot42.warpbook.util.net.NetUtils.getClientPlayer() is being called server side

**Comment by Outurnate** [comment]
Oddly enough, this function is client side only.  The only way it is called in that context is when getEffectiveSide returns CLIENT.  Forge might have changed slightly.  Was this on a dedicated server?  I will revisit this code.  I am working on a major overhaul of some of the internals

Thanks for the report!

**Comment by ZornTaov** [comment]
this went from a lan server to a dedicated server. on a lan server (that through shenanigans got port forwarded so I could play with my friend over the internet) it worked just fine. but as soon as we made the world a dedicated server it gives this error

**Comment by Outurnate** [comment]
Interesting.  I'm just finishing off for the night, but I'll be trying to repro it to tomorrow

**Comment by Outurnate** [comment]
Fixed in latest commit
