### ISSUE TITLE
Client error when teleporting

### ISSUE THREAD

**Issue by SpartanSamuel** [Outurnate/WarpBook#19]
Periodically, when I whip out my Warp Book and teleport back home I run into an issue wherein my client crashes with a fatal error right when I select my teleport location.

Below's the server logs regarding the event. Nothing else crops up during that time period.

http://pastebin.com/nib1YHVe

I didn't catch the client side logs during the event but the next time it happens I'll make another pastebin.

**Comment by Outurnate** [comment]
Fixed in the current dev version.  There's a release planned next week

**Comment by SpartanSamuel** [comment]
Hey, I'm not trying to force you into releasing anything but 'next week' has come and gone. Do you have an updated ETA on when 3.0's release is?

If Life happened, that's fine. I get that; I'm just trying to keep the line of communication open.

**Comment by Outurnate** [comment]
Sorry - I've been busy.  Got preoccupied chasing another project in the meantime

I'll see what I can get done and update the release date

**Comment by Outurnate** [comment]
I'm just about to enter testing.  Provided there are no show-stoppers, a beta will be out today or tomorrow

**Comment by SpartanSamuel** [comment]
Thanks! I appreciate you taking the time out to do this.

**Comment by Outurnate** [comment]
No worries.  I'm delaying the release one more day for some more testing/polish

**Comment by Outurnate** [comment]
One more day.  There's one last critical bug to go

**Comment by Outurnate** [comment]
Releasing now

**Comment by SpartanSamuel** [comment]
Sweet, thanks so much for pushing this out! Why did the release status go from a Release with 2.0.43 to an Alpha with 3.0, though? Not a big deal, just curious.

**Comment by Outurnate** [comment]
NBT change, and a pile of new features.  Bound to be several bugs
