### ISSUE TITLE
Warp Book Cloner texture issues

### ISSUE THREAD

**Issue by SpartanSamuel** [Outurnate/WarpBook#20]
Whenever I put the Warp Book Cloner down next to another block, the difference in height creates a hole I can look through on the adjacent block. Additionally, the bottom of the Cloner doesn't have any textures, so I can see right through it. See the short video below for a more accurate description.

https://youtu.be/YVnIzfq-7JE

MC: 1.8.9
Forge: 11.15.1.1902
WB: 3.0.0

Not really relevant to this particular issue but a question I have anyway: Can you provide a description for the new blocks and items for 3.0.0? The Curse page, forum thread, and referenced unofficial FTB wiki don't have any content regarding update 3.0.0. I have no earthly idea how to use these new things, even after a few minutes of random clicking around with/on them in various ways.

**Comment by Outurnate** [comment]
I'll look at it.  It's probably a quick fix

Documentation sucks right now.  I'm having a video review done, which should provide a quick summary.  I haven't updated the documentation on the wiki yet.  I will get that done.  For now:

Cloner:
Bottom slot is the reference book
Top slot is blank pages
Right slot is a printing plate.  Craft the plate with a blank warp book to copy it

Teleporter:
Right click with a bound page to insert.  Right click again to remove

**Comment by Outurnate** [comment]
Fixed.  I'll open a new issue for documentation

**Comment by SpartanSamuel** [comment]
That was super fast! Woah, thanks so much! If there's anything I can do to help with documentation just let me know. Probably not, but meh.

**Comment by Outurnate** [comment]
Once it's done, a quick review for clarity would be nice.  Video spotlights are always welcome as well

Just a few tweaks to the rendering options for the block were needed
