### ISSUE TITLE
Warp Book teleportation through dimension issues

### ISSUE THREAD

**Issue by chbachman** [Outurnate/WarpBook#3]
So i have been using warp book, and noticing some issues when teleporting from the nether or other dimensions to the overworld. 

Here are some good methods that i have seen work. 

https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/command/CommandTPX.java
https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/EntityHelper.java

Just pointing you to these, to help fix issues with warping in between dimensions. 

Thank you for reading.

**Comment by Outurnate** [comment]
Thanks!  Definitely looking to revamp the teleport code.  It's so kludgy right now.

**Comment by chbachman** [comment]
I had the same problems. The tpx command was originally written just as yours was. Then skyboy came through and made it ten times better. :P

**Comment by Outurnate** [comment]
Fixed with 4ccd6c4, as you've undoubtedly noticed :P
