### ISSUE TITLE
Config option to turn off getting page for death location

### ISSUE THREAD

**Issue by Dyonovan** [Outurnate/WarpBook#4]
Would it be possible to add a config option to disable getting a page when you die.

I run a pretty hard mod pack, and I really don't like people returning to there death points that easily.

Thanks

**Comment by Outurnate** [comment]
Already in.  Check the configs

----- Reply message -----

**Comment by Dyonovan** [comment]
Sorry about that. Something got missed when I updated.

**Comment by Outurnate** [comment]
No worries.  Almost thought I forgot to add it
