### ISSUE TITLE
Chunks not loading wen teleporting to/from MiningWorld dimension

### ISSUE THREAD

**Issue by leagris** [Outurnate/WarpBook#7]
Forge 10.13.0.1208
Warpbook 2.0.34
Aroma1997s Dimensional World 1.0.2.16

Teleporting to or from Mining World, chunks don't load unless disconnecting/reconnecting from server.

**Comment by Outurnate** [comment]
Will look into this.

**Comment by Outurnate** [comment]
Should be fixed in the latest ver.  Haven't been able to reproduce
